Repository boostcamp-2020/IssueTracker-24, pull requests merged in 2020-10, with the labels that each got.

#7 model 관계 설정, 서버 환경 구분 세팅
  .gitignore
  server/config/index.js
  server/models/issue.js
  server/models/user.js
Labels: :moon:Backend, :question:Question, :rainbow:Environment

#8 comment, comment-image 모델 생성 및 저장시 자동수정 코드 추가
  .vscode/settings.json
  package-lock.json
  server/models/comment-image.js
  server/models/comment.js
  test.js
Labels: :moon:Backend, :rainbow:Environment

#9 [build]: label, issueLabel model 추가
  server/models/issue-label.js
  server/models/label.js
Labels: :moon:Backend, :rainbow:Environment

#6 [build]: sequelize model 추가
  server/models/issue-image.js
  server/models/milestone.js
Labels: :moon:Backend, :rainbow:Environment, :sos:Help wanted

#10 모델 관계 설정
  server/app.js
  server/config/index.js
  server/models/comment-image.js
  server/models/comment.js
  server/models/index.js
  server/models/issue-image.js
  server/models/issue-label.js
  server/models/issue.js
  server/models/label.js
  server/models/milestone.js
  server/models/user.js
  test.js
Labels: :moon:Backend, :rainbow:Environment

#12 프론트 환경 설정
  client/.prettierrc.json
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/hello.jsx
  client/src/index.html
  client/webpack.config.js
  package-lock.json
Labels: :moon:Backend, :rainbow:Environment, :sunny:Frontend

#15 디렉토리 구조 변경
  client/package-lock.json
  client/src/App.js
  client/src/components/.keep
  client/src/lib/.keep
  client/src/pages/.keep
  client/src/system/.keep
  client/src/utils/.keep
  server/package-lock.json
  server/src/app.js
  server/src/config/index.js
  server/src/controllers/.keep
  server/src/lib/.keep
  server/src/loaders/index.js
  server/src/middlewares/.keep
  server/src/models/comment-image.js
  server/src/models/comment.js
  server/src/models/index.js
  server/src/models/issue-image.js
  server/src/models/issue.js
  server/src/models/label.js
  server/src/models/milestone.js
  server/src/models/user.js
  server/src/routes/.keep
  server/src/services/.keep
  server/src/tests/.keep
  server/src/utils/.keep
Labels: :moon:Backend, :rainbow:Environment, :sunny:Frontend

#18 프론트엔드 로그인 UI 생성
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/components/login/loginContainer/loginContainer.jsx
  client/src/components/login/loginContainer/loginContainer.scss
  client/src/components/login/loginForm/loginForm.jsx
  client/src/components/login/loginForm/loginForm.scss
  client/src/index.html
  client/webpack.config.js
  package-lock.json
  package.json
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#19 프론트엔드 Axios 로직 구현 및 로그인 로직 구현
  client/package-lock.json
  client/package.json
  client/src/lib/request.js
  client/src/system/user.js
  client/src/utils/token.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend
