Repository boostcamp-2020/IssueTracker-24, pull requests merged in 2020-11, with the labels that each got.

#102 github 관련 로직 수정
  client/package-lock.json
  client/src/components/login/loginForm/loginForm.jsx
  client/src/lib/request.js
  client/src/system/user.js
  client/webpack.config.js
  server/package-lock.json
  server/src/controllers/auth.js
Labels: :hammer:Refactor, :moon:Backend, :rainbow:Environment

#103 Axios 로직 수정
  client/src/lib/request.js
  client/src/system/user.js
Labels: :hammer:Refactor, :sunny:Frontend

#104 로그인 후 jwt 저장, 라우팅 구현
  client/src/App.jsx
  client/src/components/login/loginForm/loginForm.jsx
  client/src/pages/IssueListPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/utils/cookie.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#105 [fix] : 버튼 scss 수정
  client/src/components/.keep
  client/src/components/login/loginForm/loginForm.scss
  client/src/pages/.keep
Labels: :sunny:Frontend, :tea:Bugfix : web

#108 이슈 목록 컴포넌트 작성
  client/src/App.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/IssueLogo.jsx
  client/src/components/login/loginContainer/login-container.scss
Labels: :hammer:Refactor, :sunny:Frontend

#107 Reducer를 사용하여 issue list의 체크박스 기능 구현
  client/src/components/issue/IssueItem.jsx
  client/src/pages/IssueListPage.jsx
  client/src/reducers/checked-issue-reducer.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#109 이슈/라벨을 확인하기 위한 dummy data 설정
  client/src/App.jsx
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/pages/IssueListPage.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#110 이슈 목록에서 이슈 안에 포함되는 라벨 컴포넌트 추가
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueLabel.jsx
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :page_facing_up: Task, :sunny:Frontend

#111 전체 이슈목록 조회 api 구현
  server/src/controllers/issue.js
  server/src/loaders/index.js
  server/src/routes/index.js
  server/src/routes/issues.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :moon:Backend, :page_facing_up: Task

#112 마일스톤 목록, 라벨 목록 조회 api 구현, 헤더 ui 생성
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  server/src/controllers/label.js
  server/src/controllers/milestone.js
  server/src/routes/index.js
  server/src/routes/labels.js
  server/src/routes/milestones.js
Labels: :1st_place_medal:Must, :moon:Backend, :page_facing_up: Task

#113 axios 로직 try-catch로 예외처리 구현
  client/src/lib/request.js
Labels: :1st_place_medal:Must, :package: Epic, :sunny:Frontend

#114 Filterbar UI 구현, 기존 UI 약간 수정
  client/public/index.html
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/label/Label.jsx
  client/src/pages/issue-list/IssueListPage.jsx
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#115 FilterBar 크기 조정 #70
  client/src/components/issue/filter/FilterBar.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#116 Navigation ui 구현
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/context/issues-context.js
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/utils/svg.js
Labels: :large_blue_diamond:Feature, :page_facing_up: Task, :sunny:Frontend

#118 filter ui 수정, svg 파일 리팩토링, 모든 유저 조회하는 api 추가
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/IssueLogo.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/login/loginForm/LoginForm.jsx
  client/src/utils/svg.js
  client/webpack.config.js
  server/src/controllers/user.js
  server/src/routes/index.js
  server/src/routes/users.js
Labels: :1st_place_medal:Must, :hammer:Refactor, :large_blue_diamond:Feature, :moon:Backend, :page_facing_up: Task, :sunny:Frontend

#120 로그인 직후 이슈페이지에서 관리될 초기 데이터를 로드한다
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
Labels: :1st_place_medal:Must, :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#121 issue 조회 api assignees 목록도 가져오도록 수정
  server/src/controllers/issue.js
  server/src/models/issue.js
  server/src/tests/issues.test.js
Labels: :hammer:Refactor, :moon:Backend

#122 axios 오류 수정, 이슈 리스트 페이지 UI 수정
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/login/loginForm/LoginForm.jsx
  client/src/utils/token.js
Labels: :hammer:Refactor, :sunny:Frontend, :tea:Bugfix : web

#123 이슈 생성페이지 간단한 ui 제작(구현중)
  client/src/App.jsx
  client/src/assets/jinhyun.png
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/new/IssueNewContent.jsx
  client/src/components/issue/new/IssueNewImage.jsx
  client/src/components/issue/new/IssueNewSelector.jsx
  client/src/components/issue/new/IssueNewTitle.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-new/IssueListNewPage.jsx
  client/src/pages/issue-new/reducer.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :page_facing_up: Task, :sunny:Frontend

#124 issue 테이블 구조 수정, axios 코드 리팩토링
  client/src/lib/.keep
  client/src/lib/axios/issue.js
  client/src/lib/axios/label.js
  client/src/lib/axios/milestone.js
  client/src/lib/axios/request.js
  client/src/lib/axios/user.js
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/system/user.js
  server/src/loaders/index.js
  server/src/models/issue.js
Labels: :hammer:Refactor, :moon:Backend, :sunny:Frontend

#125 이슈목록 페이지에서 시간정보 렌더링 구현
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/IssueLogo.jsx
  client/src/utils/svg.js
  client/src/utils/time.js
  server/src/config/index.js
  server/src/controllers/issue.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#126 이슈 생성 페이지 작성 폼 구현 완료
  client/src/components/issue/new/IssueNewContent.jsx
  client/src/components/issue/new/IssueNewTitle.jsx
  server/src/controllers/issue.js
  server/src/models/issue.js
  server/src/routes/issues.js
  server/src/routes/labels.js
  server/src/routes/milestones.js
  server/src/routes/users.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :moon:Backend, :page_facing_up: Task, :sunny:Frontend

#128 필터링 기능 구현 (필터 드롭다운 메뉴)
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterMenuDropDown.jsx
  client/src/lib/axios/user.js
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/svg.js
  server/src/controllers/user.js
  server/src/routes/users.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#129 이슈 목록 페이지 toolbar UI 및 dropdown component 구현
  client/src/components/issue/DropDownIcon.jsx
  client/src/components/issue/ToolBarContainer.jsx
  client/src/components/issue/toolbar/AssigneeMenuDropDown.jsx
  client/src/components/issue/toolbar/AuthorMenuDropDown.jsx
  client/src/components/issue/toolbar/FourFilterTools.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/components/issue/toolbar/MilestoneMenuDropDown.jsx
  client/src/components/issue/toolbar/ToolBar.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
Labels: :large_blue_diamond:Feature, :package: Epic, :sunny:Frontend

#130 issue 생성페이지 css 수정
  client/src/components/issue/new/IssueNewContent.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#131 이슈 생성 페이지 우측의 Sidebar UI 구현
  client/src/App.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/components/issue/new/IssueNewContent.jsx
  client/src/components/issue/new/IssueNewImage.jsx
  client/src/components/issue/new/sidebar/Dropdown.jsx
  client/src/components/issue/new/sidebar/Heading.jsx
  client/src/components/issue/new/sidebar/LabelOption.jsx
  client/src/components/issue/new/sidebar/MilestoneOption.jsx
  client/src/components/issue/new/sidebar/Sidebar.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/components/issue/new/sidebar/UserOption.jsx
  client/src/components/login/loginContainer/login-container.scss
  client/src/components/login/loginForm/LoginForm.jsx
  client/src/pages/issue-new/IssueListNewPage.jsx
  client/src/utils/svg.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :sunny:Frontend

#132 이슈 목록 페이지 리팩터링 및 개별, 전체 체크박스 기능 구현
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/toolbar/ToolBar.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/checkbox.js
Labels: :1st_place_medal:Must, :hammer:Refactor, :sunny:Frontend

#133 리팩토링, body 이벤트 구현
  client/src/App.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/issue/filter/FilterMenuDropDown.jsx
  client/src/components/login/login-container/LoginContainer.jsx
  client/src/components/login/login-container/login-container.scss
  client/src/components/login/login-form/LoginForm.jsx
  client/src/components/login/login-form/login-form.scss
  client/src/components/login/loginForm/login-form.scss
  client/src/pages/LoginPage.jsx
  client/src/pages/issue-new/IssueNewPage.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#135 컴포넌트 리팩토링 수정
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/IssueLogo.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/new/IssueNewContent.jsx
  client/src/components/issue/new/IssueNewImage.jsx
  client/src/components/issue/new/IssueNewSelector.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#136 UI 개선 및 코드 리팩토링
  client/src/App.jsx
  client/src/components/common/DropDownIcon.jsx
  client/src/components/common/Label.jsx
  client/src/components/common/ProfileImage.jsx
  client/src/components/common/SmallLabel.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/issue/filter/FilterMenuDropDown.jsx
  client/src/components/issue/new/IssueNewImage.jsx
  client/src/components/issue/new/sidebar/LabelOption.jsx
  client/src/components/issue/toolbar/AssigneeMenuDropDown.jsx
  client/src/components/issue/toolbar/AuthorMenuDropDown.jsx
  client/src/components/issue/toolbar/FourFilterTools.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/components/issue/toolbar/MilestoneMenuDropDown.jsx
  client/src/components/login/login-form/LoginForm.jsx
  client/src/lib/axios/user.js
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/pages/issue-new/IssueNewPage.jsx
  server/src/controllers/issue.js
  server/src/controllers/user.js
  server/src/passport/github-strategy.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#137 [test] : 테스트 코드 작성
  server/package-lock.json
  server/package.json
  server/src/tests/labels.test.js
  server/src/tests/milestones.test.js
Labels: :moon:Backend, :palm_tree:test

#138 오류 수정, 렌더링 성능 최적화
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/IssueLogo.jsx
Labels: :hammer:Refactor, :sunny:Frontend, :tea:Bugfix : web

#139 [test] : 프론트엔드 렌더링 테스트
  client/babel.config.js
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/tests/DropDownIcon.test.js
  client/src/tests/Label.test.js
  client/src/tests/ProfileImage.test.js
  client/src/tests/__snapshots__/DropDownIcon.test.js.snap
  client/src/tests/__snapshots__/Label.test.js.snap
  client/src/tests/__snapshots__/ProfileImage.test.js.snap
Labels: :palm_tree:test, :sunny:Frontend

#140 이슈 목록 페이지의 검색창 UI 구현 및 검색창 text를 context로 등록
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/issue/filter/FilterForm.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/utils/svg.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :page_facing_up: Task, :sunny:Frontend

#141 Load Spinner 추가 및 이슈생성페이지 context 추가 (수정 진행중)
  client/public/index.html
  client/src/components/common/Spinner.js
  client/src/components/issue/new/sidebar/Dropdown.jsx
  client/src/components/issue/new/sidebar/Sidebar.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-new/IssueNewPage.jsx
  client/src/pages/issue-new/reducer.js
  server/src/controllers/issue.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#145 마일스톤 UI 생성
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/common/LabelComponent.jsx
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/components/milestone/CreateMilestone.jsx
  client/src/components/milestone/MilestoneHeader.jsx
  client/src/components/milestone/MilestoneList.jsx
  client/src/components/milestone/MilestoneListLeft.jsx
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/components/milestone/MilestoneSelectMenu.jsx
  client/src/pages/milestone-list/MilestonePage.jsx
  client/src/utils/svg.js
  server/package-lock.json
Labels: :1st_place_medal:Must, :page_facing_up: Task, :sunny:Frontend

#146 filtering 시 검색창 적용 및 검색창 초기화 컴포넌트 구현
  client/src/components/issue/FilterClearButton.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterForm.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/filter-text.js
  client/src/utils/svg.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#147 4개의 filter 버튼 관련 이벤트 구현
  client/src/components/issue/toolbar/AssigneeMenuDropDown.jsx
  client/src/components/issue/toolbar/AuthorMenuDropDown.jsx
  client/src/components/issue/toolbar/FourFilterTools.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/components/issue/toolbar/MilestoneMenuDropDown.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/filter-text.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :sunny:Frontend

#148 마일스톤 목록 페이지(마일스톤 api 연동, 마일스톤 시간 함수 구현, 마일스톤 open, closed 개수 구하는 로직 구현
  client/src/components/common/GreenButton.jsx
  client/src/components/milestone/CreateMilestone.jsx
  client/src/components/milestone/MilestoneHeader.jsx
  client/src/components/milestone/MilestoneList.jsx
  client/src/components/milestone/MilestoneListLeft.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/pages/milestone-list/MilestonePage.jsx
  client/src/pages/milestone-list/reducer.js
  client/src/utils/time.js
Labels: :moon:Backend, :page_facing_up: Task, :sunny:Frontend

#149 마일스톤 생성 페이지 리팩토링, 공통 컴포넌트 사용하도록 리팩토링
  client/src/components/common/GreenButton.jsx
  client/src/components/issue/CreateButton.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/new/IssueNewContent.jsx
  client/src/components/milestone/MilestoneForm.jsx
  client/src/pages/MilestoneNewPage.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#151 이슈 생성페이지 sidebar 관련 ui 수정 및 이벤트 구현(진행중)
  client/src/components/common/ProfileImage.jsx
  client/src/components/common/SmallLabel.jsx
  client/src/components/common/Spinner.js
  client/src/components/issue/new/sidebar/Dropdown.jsx
  client/src/components/issue/new/sidebar/Heading.jsx
  client/src/components/issue/new/sidebar/LabelOption.jsx
  client/src/components/issue/new/sidebar/MilestoneOption.jsx
  client/src/components/issue/new/sidebar/SelectedLabel.jsx
  client/src/components/issue/new/sidebar/Sidebar.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/components/issue/new/sidebar/UserOption.jsx
  client/src/pages/issue-new/IssueNewPage.jsx
  client/src/pages/issue-new/reducer.js
  client/src/utils/svg.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#153 마일스톤 편집 페이지 구현
  client/src/App.jsx
  client/src/components/common/GreyButton.jsx
  client/src/components/common/LabelComponent.jsx
  client/src/components/milestone/InputDate.jsx
  client/src/components/milestone/MilestoneCreateForm.jsx
  client/src/components/milestone/MilestoneEditForm.jsx
  client/src/lib/axios/milestone.js
  client/src/pages/MilestoneEditPage.jsx
  client/src/pages/MilestoneNewPage.jsx
  client/src/utils/time.js
  server/src/controllers/milestone.js
  server/src/routes/milestones.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#155 이슈 생성페이지 side-bar 완성
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/issue/new/sidebar/Dropdown.jsx
  client/src/components/issue/new/sidebar/LabelOption.jsx
  client/src/components/issue/new/sidebar/MilestoneOption.jsx
  client/src/components/issue/new/sidebar/ProgressBar.jsx
  client/src/components/issue/new/sidebar/SelectedMilestone.jsx
  client/src/components/issue/new/sidebar/Sidebar.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/pages/issue-new/IssueNewPage.jsx
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend, :tea:Bugfix : build

#156 이슈 목록 페이지에서 이슈 필터 기능 구현
  client/src/components/issue/FilterClearButton.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/filter-issue.js
  client/src/utils/filter-text.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :sunny:Frontend

#154 마일스톤 목록 페이지 구현(마일스톤 게이지와 이슈 연동, 마일스톤 삭제 api 생성)
  client/src/components/common/DropDownIcon.jsx
  client/src/components/common/GreenButton.jsx
  client/src/components/common/LabelComponent.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/milestone/MilestoneList.jsx
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/components/milestone/MilestoneModal.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/components/milestone/MilestoneSelectMenu.jsx
  client/src/pages/milestone-list/MilestonePage.jsx
  client/src/pages/milestone-list/reducer.js
  server/package-lock.json
  server/package.json
  server/src/controllers/milestone.js
  server/src/loaders/index.js
  server/src/routes/milestones.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#158 이슈 PATCH API, axios 함수 구현
  client/src/lib/axios/issue.js
  server/package-lock.json
  server/src/controllers/issue.js
  server/src/routes/issues.js
  server/src/services/.keep
  server/src/services/issue.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#159 이슈 목록 없을 떄 보여지는 컴포넌트 구현 및 mark as 버튼 관련 이벤트 구현
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/MenuContainer.jsx
  client/src/components/issue/NoIssueContent.jsx
  client/src/components/issue/filter/FilterBar.jsx
  client/src/components/issue/filter/FilterForm.jsx
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/pages/issue-list/IssueListPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/utils/svg.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#160 [feature] : 마일스톤 목록 페이지 구현 및 라우팅
  client/src/components/milestone/MilestoneCreateForm.jsx
  client/src/components/milestone/MilestoneList.jsx
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/components/milestone/MilestoneModal.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/lib/axios/milestone.js
  client/src/pages/milestone-list/MilestonePage.jsx
  client/src/pages/milestone-list/reducer.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#162 이슈 상세 페이지 제목 수정기능, 내용 Edit 모드 구분
  client/src/components/issue/detail/Issue.jsx
  client/src/components/issue/detail/IssueContainer.jsx
  client/src/components/issue/detail/IssueDetailPageHeader.jsx
  client/src/components/issue/detail/IssueForm.jsx
  client/src/components/issue/detail/IssueInfo.jsx
  client/src/components/issue/detail/IssueItemHeader.jsx
  client/src/components/issue/detail/SidebarContainer.jsx
  client/src/components/issue/detail/TitleForm.jsx
  client/src/pages/IssueDetailPage.jsx
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#163 라벨 목록 페이지 ui 구현
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/components/common/SelectedLabel.jsx
  client/src/components/issue/new/sidebar/LabelOption.jsx
  client/src/components/issue/new/sidebar/MilestoneOption.jsx
  client/src/components/issue/new/sidebar/Sidebar.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/components/label/LabelItem.jsx
  client/src/components/label/LabelListContainer.jsx
  client/src/components/label/Navigation.jsx
  client/src/components/label/NavigationTabItem.jsx
  client/src/components/label/PageBody.jsx
  client/src/pages/label-list/LabelListPage.jsx
  client/src/pages/label-list/reducer.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#164 이슈 목록 페이지에서 issue를 open/close로 수정하는 이벤트 구현
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/lib/axios/request.js
  client/src/pages/issue-list/reducer.js
Labels: :large_blue_diamond:Feature

#165 이슈 상세 페이지 사이드바 구현(클릭 시 목록 나오게 구현, 조회 api 연동)
  client/src/components/common/sidebar/Assignee.jsx
  client/src/components/common/sidebar/Label.jsx
  client/src/components/common/sidebar/Milestone.jsx
  client/src/components/common/sidebar/Sidebar.jsx
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
  client/src/components/common/sidebar/SidebarItemTitle.jsx
  client/src/components/issue/detail/SidebarContainer.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/pages/IssueDetailPage.jsx
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#166 레이블 생성 UI 구현
  client/src/components/label/LabelCreateContainer.jsx
  client/src/components/label/Navigation.jsx
  client/src/components/label/common/WriteContainer.jsx
  client/src/components/label/common/WriteContent.jsx
  client/src/pages/label-list/LabelListPage.jsx
  client/src/utils/color.js
  client/src/utils/svg.js
Labels: :1st_place_medal:Must, :large_blue_diamond:Feature, :sunny:Frontend

#169 이슈 상세페이지 사이드바 제외한 기능 구현, 짜잘한 리팩토링
  client/src/components/Header.jsx
  client/src/components/common/GreenButton.jsx
  client/src/components/common/GreyButton.jsx
  client/src/components/common/Label.jsx
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueItem.jsx
  client/src/components/issue/detail/Comment.jsx
  client/src/components/issue/detail/CommentForm.jsx
  client/src/components/issue/detail/ContentButtonContainer.jsx
  client/src/components/issue/detail/FileContainer.jsx
  client/src/components/issue/detail/Issue.jsx
  client/src/components/issue/detail/IssueContainer.jsx
  client/src/components/issue/detail/IssueForm.jsx
  client/src/components/issue/detail/IssueInfo.jsx
  client/src/components/issue/detail/IssueItemHeader.jsx
  client/src/components/milestone/DescriptionArea.jsx
  client/src/components/milestone/MilestoneList.jsx
  client/src/components/milestone/MilestoneListLeft.jsx
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/lib/axios/issue.js
  server/src/controllers/issue.js
  server/src/models/comment.js
  server/src/routes/issues.js
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#170 이슈상세페이지 사이드바 css 수정
  client/src/components/common/sidebar/SidebarItemTitle.jsx
  client/src/components/issue/detail/SidebarContainer.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#171 close -> closed 오류 수정
  client/src/components/issue/IssueContainer.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/detail/ClosedLabel.jsx
  client/src/components/issue/detail/CommentForm.jsx
  client/src/components/issue/detail/IssueDetailPageHeader.jsx
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/components/milestone/MilestoneEditForm.jsx
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/components/milestone/MilestoneModal.jsx
  client/src/components/milestone/MilestoneNav.jsx
  client/src/pages/MilestoneEditPage.jsx
  client/src/pages/issue-list/reducer.js
  client/src/pages/milestone-list/MilestonePage.jsx
  client/src/pages/milestone-list/reducer.js
  client/src/utils/filter-issue.js
  client/src/utils/svg.js
  server/src/controllers/issue.js
Labels: :sunny:Frontend, :tea:Bugfix : web

#174 이슈상세 페이지 sidebar 관련 API 및 Axios 함수 구현
  client/src/components/milestone/MilestoneListRight.jsx
  client/src/lib/axios/issue.js
  client/src/pages/milestone-list/reducer.js
  server/src/controllers/issue.js
  server/src/routes/issues.js
Labels: :large_blue_diamond:Feature, :moon:Backend, :sunny:Frontend

#172 이슈 상세페이지 check 표현
  client/src/components/common/sidebar/Assignee.jsx
  client/src/components/common/sidebar/Label.jsx
  client/src/components/common/sidebar/Milestone.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#173 Nav 재사용 및 css 수정
  client/src/components/common/Label.jsx
  client/src/components/common/Navigation.jsx
  client/src/components/common/NavigationItem.jsx
  client/src/components/common/SelectedLabel.jsx
  client/src/components/issue/IssueContent.jsx
  client/src/components/issue/Navigation.jsx
  client/src/components/issue/NavigationContainer.jsx
  client/src/components/label/DeleteModal.jsx
  client/src/components/label/LabelItem.jsx
  client/src/components/milestone/MilestoneHeader.jsx
  client/src/lib/axios/label.js
  client/src/pages/label-list/reducer.js
  server/src/controllers/label.js
  server/src/routes/labels.js
Labels: :hammer:Refactor, :sunny:Frontend

#176 이슈 상세 페이지 사이드바 구현
  client/src/components/common/sidebar/Assignee.jsx
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
Labels: :hammer:Refactor, :large_blue_diamond:Feature

#177 CSS 및 warning 수정
  client/src/components/issue/IssueContent.jsx
  client/src/components/label/LabelCreateContainer.jsx
  client/src/components/label/common/WriteContainer.jsx
  client/src/components/milestone/MilestoneNewHeader.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#178 label item 관련 css 수정
  client/src/components/label/LabelItem.jsx
  client/src/components/label/common/ColorContent.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#179 이슈 상세페이지 사이드바 마일스톤 부분 구현
  client/src/components/common/sidebar/Milestone.jsx
  client/src/components/common/sidebar/Sidebar.jsx
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
  client/src/components/issue/detail/SidebarContainer.jsx
  server/src/controllers/issue.js
Labels: :hammer:Refactor, :sunny:Frontend

#180 이슈 상세페이지 라벨 구현
  client/src/components/common/Label.jsx
  client/src/components/common/sidebar/Label.jsx
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
  client/src/lib/axios/issue.js
  client/src/lib/axios/request.js
  client/src/pages/issue-new/IssueNewPage.jsx
  client/src/utils/time.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#182 [refactor] : 코드 리팩토링
  client/src/lib/.keep
  server/src/controllers/auth.js
  server/src/controllers/issue.js
  server/src/controllers/label.js
  server/src/controllers/milestone.js
  server/src/controllers/user.js
  server/src/loaders/index.js
  server/src/middlewares/auth.js
  server/src/tests/issues.test.js
  server/src/tests/labels.test.js
  server/src/tests/milestones.test.js
  server/src/utils/.keep
  server/src/utils/response-code.js
Labels: :hammer:Refactor

#183 [refactor]: 코드, 스타일 리팩토링
  README.md
  client/public/index.html
  client/src/components/Header.jsx
  client/src/components/common/sidebar/Assignee.jsx
  client/src/components/common/sidebar/Label.jsx
  client/src/components/common/sidebar/Milestone.jsx
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/issue/detail/Issue.jsx
  client/src/components/issue/filter/FilterMenuDropDown.jsx
  client/src/components/issue/toolbar/AssigneeMenuDropDown.jsx
  client/src/components/issue/toolbar/AuthorMenuDropDown.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/components/issue/toolbar/MarkAsTool.jsx
  client/src/components/issue/toolbar/MilestoneMenuDropDown.jsx
  client/src/components/issue/toolbar/common/DetailsItem.jsx
  client/src/components/issue/toolbar/common/DetailsMenuDropDown.jsx
  client/src/pages/issue-new/IssueNewPage.jsx
  client/src/utils/svg.js
Labels: :hammer:Refactor

#184 오류수정, 리팩토링
  client/src/components/common/sidebar/SidebarItem.jsx
  client/src/components/common/sidebar/SidebarItemModal.jsx
  client/src/components/issue/new/sidebar/Dropdown.jsx
  client/src/components/issue/new/sidebar/SidebarItem.jsx
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
  client/src/components/issue/toolbar/common/DetailsItem.jsx
  client/src/components/issue/toolbar/common/DetailsMenuDropDown.jsx
  client/src/pages/label-list/LabelListPage.jsx
  client/src/pages/milestone-list/MilestonePage.jsx
Labels: :hammer:Refactor, :sunny:Frontend

#186 [fix] : css 수정
  client/src/components/common/Label.jsx
  client/src/components/issue/detail/IssueInfo.jsx
  client/src/components/issue/detail/IssueItemHeader.jsx
  client/src/components/issue/new/IssueNewContent.jsx
Labels: :hammer:Refactor, :tea:Bugfix : web

#187 [fix] : css 수정
  client/src/components/issue/toolbar/LabelMenuDropDown.jsx
Labels: :tea:Bugfix : web
